import type {
  Category,
  Department,
  Inquiry,
  Issue,
  RoleProfile,
} from "./types";

export const departments: Department[] = [
  "市民税課",
  "高齢福祉課",
  "道路維持課",
  "子育て支援課",
  "環境政策課",
  "観光振興課",
  "総務課",
];

export const categories: Category[] = [
  "税",
  "暮らし",
  "福祉",
  "道路・交通",
  "子育て・教育",
  "環境",
  "イベント・観光",
  "行政手続",
  "その他",
];

export const categoryToDepartment: Record<Category, Department> = {
  税: "市民税課",
  暮らし: "総務課",
  福祉: "高齢福祉課",
  "道路・交通": "道路維持課",
  "子育て・教育": "子育て支援課",
  環境: "環境政策課",
  "イベント・観光": "観光振興課",
  行政手続: "総務課",
  その他: "総務課",
};

export const seedInquiries: Inquiry[] = [
  {
    id: "INQ-2026-0418",
    receivedAt: "2026-04-28 09:12",
    channel: "メール",
    citizenName: "佐藤 健一",
    citizenAge: 42,
    citizenArea: "中央",
    body: "住民税の計算方法について、給与明細との差額の理由がわかりません。市のWebサイトを見ても算出根拠が示されていない箇所があり、毎年問い合わせをしています。説明資料を改善できないでしょうか。",
    summary:
      "住民税の計算根拠の説明がわかりにくく、毎年同様の問い合わせが発生している",
    category: "税",
    department: "市民税課",
    status: "対応中",
    sentiment: "建設的",
    urgency: 3,
    importance: 4,
    triage: "市政反映",
    relatedIssueIds: ["ISS-001"],
    citizenId: "C-2026-00471",
    staffNote: "Web改修の検討に回付済",
    comments: [
      {
        id: "cm-seed-0418-1",
        at: "2026-04-28 14:20",
        authorRole: "staff",
        authorName: "市民税課 担当",
        body: "確認しました。同様のお問い合わせが今月複数件あるため、課題リスト ISS-001 に紐づけました。Web改修の優先度を上げて検討します。",
      },
      {
        id: "cm-seed-0418-2",
        at: "2026-04-29 09:05",
        authorRole: "staff",
        authorName: "市民税課 課長",
        body: "通知書の様式変更は税務システムベンダーとの調整が必要。来週ベンダー打合せの議題にあげてください。",
      },
    ],
  },
  {
    id: "INQ-2026-0419",
    receivedAt: "2026-04-28 10:34",
    channel: "メール",
    citizenName: "山田 千鶴",
    citizenAge: 67,
    citizenArea: "東町",
    body: "前回市民税課に電話で相談したのですが、その内容が福祉の窓口で全く共有されていませんでした。同じ説明を何度もしなければならず、高齢者には負担です。",
    summary:
      "部署間で相談内容が共有されておらず、市民が同じ説明を繰り返す負担が発生",
    category: "行政手続",
    department: "総務課",
    status: "確認中",
    sentiment: "不満",
    urgency: 4,
    importance: 5,
    triage: "市政反映",
    relatedIssueIds: ["ISS-004"],
    isException: true,
    staffNote: "部署横断の課題。市長判断案件として上申候補",
    comments: [
      {
        id: "cm-seed-0419-1",
        at: "2026-04-28 16:50",
        authorRole: "staff",
        authorName: "総務課 担当",
        body: "受付内容を確認しました。同様のご指摘が高齢福祉課でも記録されています。部署横断の連携課題として ISS-004 に紐づけます。",
      },
      {
        id: "cm-seed-0419-2",
        at: "2026-04-29 10:15",
        authorRole: "mayor",
        authorName: "市長",
        body: "個別対応では限界がある。次回市政会議の議題に。総務課で論点整理をお願いします。",
      },
      {
        id: "cm-seed-0419-3",
        at: "2026-04-29 11:00",
        authorRole: "staff",
        authorName: "総務課 課長",
        body: "承知しました。各部署にヒアリングを実施し、論点を取りまとめて来週報告します。",
      },
    ],
  },
  {
    id: "INQ-2026-0420",
    receivedAt: "2026-04-28 11:02",
    channel: "メール",
    citizenName: "鈴木 拓海",
    citizenAge: 35,
    citizenArea: "北町",
    body: "通学路の側溝の蓋が一部破損しており、子どもが通る時間帯に危険です。場所は北小学校の南側交差点付近です。早めに対応をお願いします。",
    summary: "通学路の側溝破損、児童の安全に関わる箇所の早期補修要望",
    category: "道路・交通",
    department: "道路維持課",
    status: "対応中",
    sentiment: "情報提供",
    urgency: 5,
    importance: 4,
    triage: "現場対応",
    relatedIssueIds: ["ISS-002"],
    comments: [
      {
        id: "cm-seed-0420-1",
        at: "2026-04-28 12:10",
        authorRole: "staff",
        authorName: "道路維持課 担当",
        body: "現地確認しました。破損箇所は2箇所、深さ約5cm。応急処置としてカラーコーンを設置済みです。本格補修は今週中に着手します。",
      },
      {
        id: "cm-seed-0420-2",
        at: "2026-04-28 18:30",
        authorRole: "staff",
        authorName: "道路維持課 主任",
        body: "通学路は児童の安全に直結するため、最優先で対応します。報告者の方には対応完了後にメールで状況をお伝えします。",
      },
    ],
  },
  {
    id: "INQ-2026-0421",
    receivedAt: "2026-04-28 13:48",
    channel: "メール",
    citizenName: "高橋 美穂",
    citizenAge: 31,
    citizenArea: "西町",
    body: "子育て世帯向けの一時預かり制度の予約方法が複雑で、平日の窓口しか受け付けていないのが負担です。オンラインでの予約に対応していただきたいです。",
    summary: "一時預かり制度のオンライン予約導入要望、共働き世帯の利便性課題",
    category: "子育て・教育",
    department: "子育て支援課",
    status: "受付済",
    sentiment: "建設的",
    urgency: 3,
    importance: 4,
    triage: "市政反映",
    relatedIssueIds: ["ISS-003"],
  },
  {
    id: "INQ-2026-0422",
    receivedAt: "2026-04-28 14:30",
    channel: "電話",
    citizenName: "伊藤 義雄",
    citizenAge: 71,
    citizenArea: "南町",
    body: "ごみ収集日の祝日対応が変更になっていることを知らず、収集されないことが続きました。広報の方法を見直してほしいです。",
    summary:
      "祝日のごみ収集日変更が高齢者層に届いていない、広報手段の見直し要望",
    category: "環境",
    department: "環境政策課",
    status: "確認中",
    sentiment: "不満",
    urgency: 2,
    importance: 3,
    triage: "現場対応",
    relatedIssueIds: ["ISS-005"],
  },
  {
    id: "INQ-2026-0423",
    receivedAt: "2026-04-28 15:11",
    channel: "メール",
    citizenName: "田中 真理",
    citizenAge: 39,
    citizenArea: "駅前",
    body: "住民税の特別徴収の通知書が、内訳が省略されていてわかりません。全国で同様の様式と思いますが、参考事例として他自治体のような内訳の明示を検討いただけませんか。",
    summary: "住民税通知書の様式改善要望、他自治体の事例を参考にした提案",
    category: "税",
    department: "市民税課",
    status: "対応中",
    sentiment: "建設的",
    urgency: 3,
    importance: 4,
    triage: "市政反映",
    relatedIssueIds: ["ISS-001"],
  },
  {
    id: "INQ-2026-0424",
    receivedAt: "2026-04-28 16:02",
    channel: "メール",
    citizenName: "渡辺 武",
    citizenAge: 58,
    citizenArea: "緑町",
    body: "市役所の駐車場が混雑しており、高齢の親を連れて行く際に毎回時間がかかります。予約制や時間帯案内などの工夫はできないでしょうか。",
    summary: "市役所駐車場の混雑、来庁者向けの予約・案内の仕組みに関する提案",
    category: "暮らし",
    department: "総務課",
    status: "受付済",
    sentiment: "建設的",
    urgency: 2,
    importance: 3,
    triage: "現場対応",
    relatedIssueIds: ["ISS-006"],
  },
  {
    id: "INQ-2026-0425",
    receivedAt: "2026-04-28 16:45",
    channel: "Web",
    citizenName: "中村 葉子",
    citizenAge: 45,
    citizenArea: "中央",
    body: "住民税の計算がわかりにくいです。FAQをもっと充実させてください。",
    summary: "住民税FAQ拡充の要望",
    category: "税",
    department: "市民税課",
    status: "受付済",
    sentiment: "建設的",
    urgency: 2,
    importance: 3,
    triage: "現場対応",
    relatedIssueIds: ["ISS-001"],
  },
  {
    id: "INQ-2026-0426",
    receivedAt: "2026-04-29 08:50",
    channel: "メール",
    citizenName: "小林 達也",
    citizenAge: 28,
    citizenArea: "東町",
    body: "公園の遊具が老朽化しており、塗装の剥がれが目立ちます。子どもが安全に遊べるよう優先的に補修いただきたいです。",
    summary: "公園遊具の老朽化、安全面からの補修要望",
    category: "道路・交通",
    department: "道路維持課",
    status: "対応中",
    sentiment: "情報提供",
    urgency: 4,
    importance: 3,
    triage: "現場対応",
    relatedIssueIds: ["ISS-002"],
  },
  {
    id: "INQ-2026-0427",
    receivedAt: "2026-04-29 10:05",
    channel: "メール",
    citizenName: "加藤 直樹",
    citizenAge: 33,
    citizenArea: "西町",
    body: "保育園入所の申請書類が紙のみで、共働きで提出に行く時間が取れません。電子申請を導入してほしいです。",
    summary: "保育園入所申請の電子化要望",
    category: "子育て・教育",
    department: "子育て支援課",
    status: "受付済",
    sentiment: "建設的",
    urgency: 3,
    importance: 4,
    triage: "市政反映",
    relatedIssueIds: ["ISS-003"],
  },
  {
    id: "INQ-2026-0428",
    receivedAt: "2026-04-29 11:30",
    channel: "メール",
    citizenName: "松本 美樹",
    citizenAge: 52,
    citizenArea: "南町",
    body: "高齢の母の介護認定の更新で、市民税課と高齢福祉課で別々に書類を出すよう求められました。一度の申請で済むようにできませんか。",
    summary: "介護関連手続きの部署横断ワンストップ化要望",
    category: "福祉",
    department: "高齢福祉課",
    status: "確認中",
    sentiment: "建設的",
    urgency: 3,
    importance: 5,
    triage: "市政反映",
    relatedIssueIds: ["ISS-004"],
    isException: true,
    comments: [
      {
        id: "cm-seed-0428-1",
        at: "2026-04-29 13:00",
        authorRole: "staff",
        authorName: "高齢福祉課 担当",
        body: "市民税課と連携の上、現状の手続きフローを整理しました。両課で共通する書類は1つにまとめられる可能性があります。",
      },
    ],
  },
  {
    id: "INQ-2026-0429",
    receivedAt: "2026-04-29 13:20",
    channel: "メール",
    citizenName: "井上 修司",
    citizenAge: 60,
    citizenArea: "中央",
    body: "観光案内のWebページが古く、市内の祭事情報も最新ではありません。観光客への印象も悪く、改善を検討ください。",
    summary: "観光情報Webサイトの更新頻度・最新性の課題",
    category: "イベント・観光",
    department: "観光振興課",
    status: "受付済",
    sentiment: "建設的",
    urgency: 2,
    importance: 3,
    triage: "現場対応",
    relatedIssueIds: ["ISS-007"],
  },
  {
    id: "INQ-2026-0430",
    receivedAt: "2026-04-29 14:10",
    channel: "目安箱",
    citizenName: "匿名",
    citizenArea: "東町",
    body: "市役所1階の目安箱に投函されたご意見：行政手続きで複数の課を回らなければならない場合、案内図だけでは分かりにくく、高齢の親と来庁すると毎回迷います。総合受付に「手続きの流れ」を相談できる窓口を設置してほしいです。",
    summary: "総合受付で手続きフローを案内する窓口の設置要望",
    category: "行政手続",
    department: "総務課",
    status: "確認中",
    sentiment: "建設的",
    urgency: 3,
    importance: 4,
    triage: "市政反映",
    relatedIssueIds: ["ISS-004", "ISS-006"],
    isException: true,
    staffNote: "目安箱経由。市長直送案件として共有",
    comments: [
      {
        id: "cm-seed-0430-1",
        at: "2026-04-29 16:00",
        authorRole: "staff",
        authorName: "総務課 担当",
        body: "目安箱からの直送案件として受付しました。ISS-004（部署横断連携）と関連が高いため紐付けます。",
      },
      {
        id: "cm-seed-0430-2",
        at: "2026-04-29 17:30",
        authorRole: "mayor",
        authorName: "市長",
        body: "目安箱から届いた率直な声。総合案内窓口の設置は前向きに検討したい。試行運用の可能性も含めて総務課で整理を。",
      },
    ],
  },
  {
    id: "INQ-2026-0431",
    receivedAt: "2026-04-30 09:45",
    channel: "目安箱",
    citizenName: "匿名",
    citizenArea: "南町",
    body: "目安箱経由のご意見：地域の防災訓練が形骸化しているように感じます。自治会単位で実施されていますが、参加者が固定化しており、若い世代が来ません。市として広く参加を促す仕組みを考えてほしいです。",
    summary: "地域防災訓練の若年層参加促進に関する提案",
    category: "暮らし",
    department: "総務課",
    status: "受付済",
    sentiment: "建設的",
    urgency: 2,
    importance: 4,
    triage: "市政反映",
    relatedIssueIds: [],
  },
];

export const seedIssues: Issue[] = [
  {
    id: "ISS-001",
    title: "住民税の説明資料が市民に伝わっていない",
    description:
      "住民税の計算方法・通知書の表記に関する問い合わせが直近で増加。複数の市民から同様の指摘があり、Webサイト・通知書様式の双方の改善が必要。",
    category: "税",
    departments: ["市民税課"],
    inquiryCount: 27,
    trend: "急増",
    urgency: 4,
    importance: 4,
    triage: "市政反映",
    proposal:
      "①市Webサイトの住民税FAQの全面改修、②通知書への内訳記載の追加、③確定申告時期前の重点広報。先行自治体の事例を踏まえ3ヶ月で実装可能。",
    citizenVoices: [
      "毎年同じ問い合わせをしている。説明資料を改善してほしい",
      "通知書の内訳が省略されていてわかりません",
      "FAQをもっと充実させてください",
    ],
    relatedIssueIds: ["ISS-004"],
    weeklySeries: [4, 5, 6, 8, 9, 12, 18, 27],
    status: "検討中",
    decisionLog: [],
    comments: [
      {
        id: "cm-iss-001-1",
        at: "2026-04-26 10:30",
        authorRole: "staff",
        authorName: "市民税課 課長",
        body: "確定申告期に関連したお問い合わせが急増しています。FAQ改修と通知書様式の見直しを並行で進める方針で、予算化の整理が必要です。",
      },
      {
        id: "cm-iss-001-2",
        at: "2026-04-27 14:00",
        authorRole: "staff",
        authorName: "広報課 担当",
        body: "FAQの拡充は広報課でも支援可能です。コンテンツ案ができれば、Webサイト改修と合わせて公開時期を調整します。",
      },
      {
        id: "cm-iss-001-3",
        at: "2026-04-28 09:15",
        authorRole: "mayor",
        authorName: "副市長",
        body: "通知書の様式変更は次年度ベンダー契約のタイミングで進めるのが現実的。FAQは今期中に着手して構わない。",
      },
    ],
  },
  {
    id: "ISS-002",
    title: "通学路・公園における安全インフラの劣化",
    description:
      "通学路の側溝・公園遊具など、児童の安全に関わるインフラの劣化報告が継続的に発生。緊急度が高いものを優先的に補修する仕組みが必要。",
    category: "道路・交通",
    departments: ["道路維持課"],
    inquiryCount: 14,
    trend: "増加",
    urgency: 5,
    importance: 4,
    triage: "現場対応",
    proposal:
      "①報告から現地確認までの標準対応時間の設定、②児童関連箇所の優先順位ロジック導入、③市民通報マップとの連携。",
    citizenVoices: [
      "通学路の側溝の蓋が破損しており、子どもが通る時間帯に危険です",
      "公園の遊具が老朽化しており、塗装の剥がれが目立ちます",
    ],
    relatedIssueIds: [],
    weeklySeries: [2, 3, 3, 4, 4, 6, 8, 14],
    status: "検討中",
    decisionLog: [],
    comments: [
      {
        id: "cm-iss-002-1",
        at: "2026-04-25 16:20",
        authorRole: "staff",
        authorName: "道路維持課 主任",
        body: "児童関連の優先順位ロジックは内部で運用済みですが、市民通報マップとの連携は未着手。Web開発予算の確保が必要です。",
      },
      {
        id: "cm-iss-002-2",
        at: "2026-04-28 11:40",
        authorRole: "staff",
        authorName: "教育委員会 担当",
        body: "通学路マップは教育委員会でも活用しています。データを共有できれば、危険箇所の早期把握に役立ちます。",
      },
    ],
  },
  {
    id: "ISS-003",
    title: "子育て関連手続きの紙・対面依存による負担",
    description:
      "共働き世帯から、保育園入所申請・一時預かり制度の電子化・オンライン予約を求める意見が継続。利便性向上は子育て世代の定住性にも影響。",
    category: "子育て・教育",
    departments: ["子育て支援課"],
    inquiryCount: 11,
    trend: "増加",
    urgency: 3,
    importance: 4,
    triage: "市政反映",
    proposal:
      "①一時預かりオンライン予約の試行導入、②保育園入所書類の電子申請、③申請進捗のWeb確認機能。",
    citizenVoices: [
      "一時預かり制度の予約方法が複雑で、平日の窓口しか受け付けていない",
      "保育園入所の申請書類が紙のみで、共働きで提出に行く時間が取れない",
    ],
    relatedIssueIds: [],
    weeklySeries: [3, 3, 4, 5, 6, 8, 9, 11],
    status: "検討中",
    decisionLog: [],
    comments: [
      {
        id: "cm-iss-003-1",
        at: "2026-04-27 09:10",
        authorRole: "staff",
        authorName: "子育て支援課 課長",
        body: "オンライン予約は他自治体の先行事例があり、導入ハードルは低めです。既存の予約システムベンダーに見積を依頼中。",
      },
      {
        id: "cm-iss-003-2",
        at: "2026-04-28 15:00",
        authorRole: "mayor",
        authorName: "市長",
        body: "子育て世代の定住性に直結する重要案件。今期中に試行導入できるよう進めてほしい。",
      },
    ],
  },
  {
    id: "ISS-004",
    title: "部署横断での情報連携不足",
    description:
      "複数部署にまたがる相談で、市民が同じ説明を繰り返す状態が常態化。介護・福祉・税の連携シーンでとくに顕著。市民満足度の低下要因。",
    category: "行政手続",
    departments: ["総務課", "市民税課", "高齢福祉課"],
    inquiryCount: 9,
    trend: "増加",
    urgency: 4,
    importance: 5,
    triage: "市政反映",
    proposal:
      "①相談履歴の部署横断共有DBの整備、②介護関連のワンストップ窓口の設計、③職員向けの市民履歴参照画面。",
    citizenVoices: [
      "前回市民税課に電話した内容が福祉窓口で共有されていない",
      "介護関連で市民税課と高齢福祉課に別々に書類を出す必要がある",
    ],
    relatedIssueIds: ["ISS-001"],
    weeklySeries: [1, 1, 2, 3, 4, 5, 7, 9],
    status: "検討中",
    decisionLog: [],
    comments: [
      {
        id: "cm-iss-004-1",
        at: "2026-04-26 13:30",
        authorRole: "staff",
        authorName: "総務課 課長",
        body: "現状、各部署で独立した記録システムを使っており、横断検索ができません。共有DBの設計から始める必要があります。",
      },
      {
        id: "cm-iss-004-2",
        at: "2026-04-27 10:20",
        authorRole: "staff",
        authorName: "情報システム課 担当",
        body: "個人情報の取り扱いがポイントになります。法務的なレビューを含めた検討が必要です。",
      },
      {
        id: "cm-iss-004-3",
        at: "2026-04-28 17:45",
        authorRole: "mayor",
        authorName: "副市長",
        body: "市民満足度の根本要因。法務調整含めて期限を切って進めましょう。リソース必要なら相談を。",
      },
      {
        id: "cm-iss-004-4",
        at: "2026-04-29 09:00",
        authorRole: "staff",
        authorName: "総務課 課長",
        body: "承知しました。法務・情シスを含めたタスクフォース立ち上げを起案します。",
      },
    ],
  },
  {
    id: "ISS-005",
    title: "高齢者層への広報手段の偏り",
    description:
      "祝日のごみ収集など生活情報の変更が高齢者層に届かず、結果として相談件数が増加。広報手段の見直しが必要。",
    category: "環境",
    departments: ["環境政策課"],
    inquiryCount: 6,
    trend: "横ばい",
    urgency: 2,
    importance: 3,
    triage: "現場対応",
    proposal:
      "①回覧板・町内会との連携強化、②町内会長向けの月次情報パッケージ、③紙媒体での周知ルート整理。",
    citizenVoices: [
      "ごみ収集日の祝日対応が変更になっていることを知らず、収集されない",
    ],
    relatedIssueIds: [],
    weeklySeries: [3, 3, 4, 4, 4, 5, 5, 6],
    status: "検討中",
    decisionLog: [],
    comments: [
      {
        id: "cm-iss-005-1",
        at: "2026-04-27 11:00",
        authorRole: "staff",
        authorName: "環境政策課 担当",
        body: "町内会経由の周知は効果的ですが、町内会未加入世帯への対応が課題です。広報手段を分けて整理する必要があります。",
      },
    ],
  },
  {
    id: "ISS-006",
    title: "市役所来庁時の待ち時間・駐車場混雑",
    description:
      "来庁時の駐車・待機に関する相談。電子申請推進と組み合わせた来庁数自体の削減が中長期課題。",
    category: "暮らし",
    departments: ["総務課"],
    inquiryCount: 5,
    trend: "横ばい",
    urgency: 2,
    importance: 3,
    triage: "現場対応",
    proposal: "①来庁者数のピーク時間案内、②予約来庁制度の試行。",
    citizenVoices: ["駐車場が混雑しており、毎回時間がかかる"],
    relatedIssueIds: ["ISS-003"],
    weeklySeries: [2, 2, 3, 3, 3, 4, 4, 5],
    status: "検討中",
    decisionLog: [],
  },
  {
    id: "ISS-007",
    title: "観光情報の鮮度と発信力",
    description:
      "観光案内Webサイトの情報更新が遅く、観光客・市民双方からの指摘が継続。",
    category: "イベント・観光",
    departments: ["観光振興課"],
    inquiryCount: 4,
    trend: "横ばい",
    urgency: 1,
    importance: 2,
    triage: "現場対応",
    proposal:
      "①更新フローの再設計、②町内会・商店街との情報連携、③簡易CMSの導入。",
    citizenVoices: ["観光案内のWebページが古く、市内の祭事情報も最新ではない"],
    relatedIssueIds: [],
    weeklySeries: [2, 2, 3, 3, 3, 3, 4, 4],
    status: "検討中",
    decisionLog: [],
  },
];

export const weeklySeriesLabels = [
  "3/9週",
  "3/16週",
  "3/23週",
  "3/30週",
  "4/6週",
  "4/13週",
  "4/20週",
  "4/27週",
];

export const roleProfiles: Record<"citizen" | "staff" | "mayor", RoleProfile> = {
  citizen: {
    role: "citizen",
    label: "市民の方",
    description:
      "市政へのご意見・ご要望の投稿、ご自身の問い合わせ状況のご確認",
    signInLabel: "市民番号でログイン",
    defaultId: "C-2026-00471",
    defaultName: "佐藤 健一",
    href: "/citizen",
    bullets: [
      "市政への意見・要望をオンラインで投稿",
      "過去のお問い合わせ状況を確認",
      "同じ分野で寄せられている声の総数を可視化",
    ],
  },
  staff: {
    role: "staff",
    label: "市役所職員",
    description: "受付済み問い合わせの確認・分類、課題抽出結果の確認",
    signInLabel: "職員IDでログイン",
    defaultId: "STF-1031",
    defaultName: "市民税課 担当",
    href: "/staff",
    bullets: [
      "経路を問わず一覧で問い合わせを確認",
      "重要度・所管部署で絞り込み・並べ替え",
      "課題抽出結果の確認と所管判断",
    ],
  },
  mayor: {
    role: "mayor",
    label: "市長・幹部",
    description:
      "市政全体の課題把握、優先度の高い案件の確認、改善提案の上申管理",
    signInLabel: "幹部IDでログイン",
    defaultId: "EXE-001",
    defaultName: "市長",
    href: "/mayor",
    bullets: [
      "全体ダッシュボードで月次の状況を確認",
      "重要課題ランキングで判断対象を把握",
      "改善提案の上申・着手管理",
    ],
  },
};
