import type {
  Category,
  Channel,
  Department,
  Letter,
  StaffProfile,
  Theme,
} from "./types";

export const departments: Department[] = [
  "健康医療福祉部",
  "子ども若者部",
  "教育委員会",
  "土木交通部",
  "琵琶湖環境部",
  "商工観光労働部",
  "防災危機管理局",
  "総合企画部",
];

export const categories: Category[] = [
  "医療・福祉",
  "子育て・教育",
  "道路・交通",
  "環境・琵琶湖",
  "産業・観光",
  "防災・安全",
  "県政運営・手続",
  "その他",
];

export const channels: Channel[] = ["LINE", "Webフォーム", "メール", "郵送"];

export const staffProfile: StaffProfile = {
  name: "広報課 県民の声担当",
  id: "STF-2041",
  section: "知事公室 広報課",
};

export const seedLetters: Letter[] = [
  {
    id: "LTR-2026-0341",
    receivedAt: "2026-07-14 08:42",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "30代",
    senderArea: "大津市",
    body: "子どもの医療費助成についてお願いがあります。現在は小学校卒業までが対象ですが、隣の県では高校卒業まで無料になっています。子どもが2人いて、中学生になると部活のけがなどで通院も増えます。県として対象年齢を広げることを検討してもらえないでしょうか。子育て世帯にとって医療費の負担は本当に大きいです。",
    aiSummary: "子ども医療費助成の対象年齢を高校卒業まで拡大してほしいという要望",
    aiPoints: [
      "現行制度（小学校卒業まで）と近隣県（高校卒業まで）の格差を指摘",
      "中学生以降の通院増加による家計負担が動機",
      "同種の要望が今月32件と急増中のテーマ",
    ],
    sentiment: "要望",
    aiConfidence: 94,
    category: "子育て・教育",
    department: "子ども若者部",
    priority: "高",
    aiPriorityReason:
      "子育て世帯全体に関わる制度要望で、同種の意見が今月32件と急増しているため",
    replyRequired: true,
    status: "新着",
    isFresh: true,
    log: [
      {
        at: "2026-07-14 08:42",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
    ],
  },
  {
    id: "LTR-2026-0340",
    receivedAt: "2026-07-14 07:55",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "40代",
    senderArea: "草津市",
    body: "路線バスの減便が続き、高齢の母が病院に通えなくなりつつあります。私も仕事があり毎回送迎はできません。デマンドタクシーなどの代替手段を県として支援してもらえないでしょうか。地域の足の問題は市町だけでは解決できないと思います。",
    aiSummary: "路線バス減便により高齢者の通院が困難、県による地域交通支援の要望",
    aiPoints: [
      "バス減便で通院手段を失いつつある高齢者の具体事例",
      "デマンドタクシー等の代替交通への県支援を提案",
      "市町単独では解決困難な広域課題との指摘",
    ],
    sentiment: "要望",
    aiConfidence: 91,
    category: "道路・交通",
    department: "土木交通部",
    priority: "高",
    aiPriorityReason:
      "通院手段の喪失という生活への影響が大きく、放置すると深刻化する個別事情を含むため",
    replyRequired: true,
    status: "新着",
    isFresh: true,
    log: [
      {
        at: "2026-07-14 07:55",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
    ],
  },
  {
    id: "LTR-2026-0339",
    receivedAt: "2026-07-13 21:10",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "30代",
    senderArea: "大津市",
    body: "防災アプリの通知が日本語のみで、近所に住む外国籍の方が大雨警報の意味がわからず困っていました。多言語対応ややさしい日本語での配信を検討してほしいです。",
    aiSummary: "防災アプリの多言語対応・やさしい日本語での情報配信の要望",
    aiPoints: [
      "外国籍住民が警報情報を理解できなかった具体事例",
      "多言語化とやさしい日本語の2つの改善案を提示",
    ],
    sentiment: "提案",
    aiConfidence: 88,
    category: "防災・安全",
    department: "防災危機管理局",
    priority: "中",
    aiPriorityReason:
      "災害時の安全に関わるものの、恒常的な改善提案であり直近の危険性は低いため",
    replyRequired: true,
    status: "新着",
    isFresh: true,
    log: [
      {
        at: "2026-07-13 21:10",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
    ],
  },
  {
    id: "LTR-2026-0338",
    receivedAt: "2026-07-13 18:34",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "40代",
    senderArea: "草津市",
    body: "ビワイチ（琵琶湖一周サイクリング）を楽しんでいますが、湖岸道路の一部で路肩が狭く、車との距離が近くて危険を感じる区間があります。矢羽根表示の延伸や注意喚起の看板を増やしてもらえるとありがたいです。",
    aiSummary: "ビワイチ湖岸道路の危険区間への矢羽根表示延伸・注意喚起の要望",
    aiPoints: [
      "路肩が狭く自動車との距離が近い区間の安全性を指摘",
      "矢羽根表示の延伸と看板増設という具体的な改善案",
    ],
    sentiment: "提案",
    aiConfidence: 86,
    category: "道路・交通",
    department: "土木交通部",
    priority: "中",
    aiPriorityReason:
      "事故リスクの指摘だが具体的な被害報告はなく、計画的な対応が可能なため",
    replyRequired: true,
    status: "新着",
    isFresh: true,
    log: [
      {
        at: "2026-07-13 18:34",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
    ],
  },
  {
    id: "LTR-2026-0337",
    receivedAt: "2026-07-13 10:20",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "60代",
    senderArea: "守山市",
    body: "湖岸緑地の近くに住んでいます。今年も琵琶湖の水草が岸に打ち上げられて腐り、悪臭がひどい時期になりました。回収の頻度を上げるか、沖での刈り取りを強化してもらえないでしょうか。散歩する人も減っています。",
    aiSummary: "琵琶湖岸に打ち上がる水草の腐敗臭対策として回収頻度向上・沖合刈取強化の要望",
    aiPoints: [
      "湖岸の水草腐敗による悪臭被害（毎年夏に発生）",
      "回収頻度の向上と沖合での刈り取り強化の2案を提示",
      "同種の意見が今月21件寄せられている頻出テーマ",
    ],
    sentiment: "不満",
    aiConfidence: 95,
    category: "環境・琵琶湖",
    department: "琵琶湖環境部",
    priority: "中",
    aiPriorityReason:
      "生活環境への影響が継続中で同種意見も多いが、人身への危険はないため",
    replyRequired: true,
    status: "振り分け済",
    log: [
      {
        at: "2026-07-13 10:20",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-13 11:05",
        action: "振り分け内容を確認・確定（琵琶湖環境部）",
        by: "広報課 県民の声担当",
      },
    ],
  },
  {
    id: "LTR-2026-0336",
    receivedAt: "2026-07-12 16:48",
    channel: "メール",
    senderName: "山口 恵子",
    senderAgeGroup: "40代",
    senderArea: "長浜市",
    body: "県立高校の再編計画について、対象校の保護者への説明が不足していると感じます。説明会は平日昼間のみで、働いている保護者は参加できません。夜間やオンラインでの説明会を開催し、質疑の記録を公開してください。",
    aiSummary: "県立高校再編に関する保護者説明会の開催方法改善（夜間・オンライン開催、記録公開）の要望",
    aiPoints: [
      "平日昼間のみの説明会では働く保護者が参加不可",
      "夜間・オンライン開催と質疑記録の公開を要望",
    ],
    sentiment: "不満",
    aiConfidence: 90,
    category: "子育て・教育",
    department: "教育委員会",
    priority: "中",
    aiPriorityReason:
      "説明機会の改善要望であり、開催方法の見直しで対応可能なため",
    replyRequired: true,
    status: "振り分け済",
    log: [
      {
        at: "2026-07-12 16:48",
        action: "メール経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-12 17:20",
        action: "AI振り分け（子ども若者部）を教育委員会に修正のうえ確定",
        by: "広報課 県民の声担当",
      },
    ],
  },
  {
    id: "LTR-2026-0335",
    receivedAt: "2026-07-12 09:15",
    channel: "郵送",
    senderName: "田中 正雄",
    senderAgeGroup: "70代",
    senderArea: "甲賀市",
    body: "県立病院で診察を受けましたが、予約をしていても2時間近く待たされました。高齢者には長時間の待機はこたえます。予約枠の見直しや、待ち時間が分かる仕組みを作っていただけないでしょうか。",
    aiSummary: "県立病院の外来待ち時間の長さに対する改善要望（予約枠見直し・待ち時間の可視化）",
    aiPoints: [
      "予約ありでも約2時間の待機が発生",
      "予約枠の見直しと待ち時間表示の仕組みを提案",
    ],
    sentiment: "不満",
    aiConfidence: 89,
    category: "医療・福祉",
    department: "健康医療福祉部",
    priority: "中",
    aiPriorityReason:
      "高齢者の負担軽減に関わるが、緊急対応を要する事案ではないため",
    replyRequired: true,
    status: "振り分け済",
    log: [
      {
        at: "2026-07-12 09:15",
        action: "郵送で受領、職員がスキャン登録後にAIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-12 10:02",
        action: "振り分け内容を確認・確定（健康医療福祉部）",
        by: "広報課 県民の声担当",
      },
    ],
  },
  {
    id: "LTR-2026-0334",
    receivedAt: "2026-07-11 14:30",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "50代",
    senderArea: "甲賀市",
    body: "地元の農産物直売所が後継者不足で存続の危機です。観光客にも人気の場所なので、県の6次産業化支援や担い手マッチングの制度をもっと使いやすくしてもらえないでしょうか。",
    aiSummary: "農産物直売所の後継者不足に対する県支援制度の利用しやすさ改善の要望",
    aiPoints: [
      "後継者不足による直売所存続の危機",
      "6次産業化支援・担い手マッチング制度の改善を要望",
    ],
    sentiment: "要望",
    aiConfidence: 82,
    category: "産業・観光",
    department: "商工観光労働部",
    priority: "低",
    aiPriorityReason:
      "中長期的な支援制度の改善要望であり、即時対応の必要性は低いため",
    replyRequired: true,
    status: "振り分け済",
    log: [
      {
        at: "2026-07-11 14:30",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-11 15:40",
        action: "振り分け内容を確認・確定（商工観光労働部）",
        by: "広報課 県民の声担当",
      },
    ],
  },
  {
    id: "LTR-2026-0333",
    receivedAt: "2026-07-10 19:22",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "30代",
    senderArea: "彦根市",
    body: "小学生の子どもが通学で使う県道の歩道が狭く、大型トラックが通るたびにひやっとします。ガードレールもない区間があります。通学時間帯だけでも安全対策を強化してもらえないでしょうか。場所は彦根市内の県道2号沿いです。",
    aiSummary: "通学路となっている県道の歩道が狭くガードレールも未設置、安全対策強化の要望",
    aiPoints: [
      "通学時間帯に大型車両とのすれ違いで危険を実感",
      "ガードレール未設置区間の存在を指摘",
      "県道2号沿い（彦根市内）と場所が特定されている",
    ],
    sentiment: "要望",
    aiConfidence: 93,
    category: "道路・交通",
    department: "土木交通部",
    priority: "高",
    aiPriorityReason:
      "児童の安全に直結し、危険箇所が具体的に特定されているため",
    replyRequired: true,
    status: "回答案作成中",
    draft: {
      body: "このたびは「知事への手紙」にご意見をお寄せいただき、ありがとうございます。\n通学路となっている県道の歩道が狭く、安全対策の強化を求めるご意見として拝見いたしました。\n\nご指摘の彦根市内の県道2号沿いの区間につきましては、所管の土木事務所において現地の状況を確認いたします。緊急に対応が必要な場合は路面標示や注意喚起看板の設置などの応急措置を行うとともに、歩道の拡幅やガードレールの設置といった抜本的な対策については、地域の交通量や通学路交通安全プログラムに基づく優先度を踏まえ、計画的な整備を検討してまいります。\n\n今後とも、県民の皆さまの声を大切にした県政運営に努めてまいりますので、引き続きお気づきの点がございましたらお聞かせください。\n\n（所管：土木交通部）",
      generatedAt: "2026-07-10 19:24",
      generator: "AI",
      edited: true,
    },
    log: [
      {
        at: "2026-07-10 19:22",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-10 19:24",
        action: "AIが回答案を生成",
        by: "システム",
      },
      {
        at: "2026-07-11 09:12",
        action: "回答案を編集（現地確認・通学路プログラムの記載を追加）",
        by: "広報課 県民の声担当",
      },
    ],
  },
  {
    id: "LTR-2026-0332",
    receivedAt: "2026-07-10 11:05",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "30代",
    senderArea: "守山市",
    body: "子育て支援センターが平日しか開いておらず、共働きだと利用できません。土日にも開放してもらえるとありがたいです。同じように感じている親は周りにも多いです。",
    aiSummary: "子育て支援センターの土日開放の要望（共働き世帯の利用機会確保）",
    aiPoints: [
      "平日のみの開館では共働き世帯が利用不可",
      "周囲にも同様のニーズがあるとの言及",
    ],
    sentiment: "要望",
    aiConfidence: 87,
    category: "子育て・教育",
    department: "子ども若者部",
    priority: "中",
    aiPriorityReason:
      "制度運用の改善要望で、運営主体の市町との調整を要するため",
    replyRequired: true,
    status: "回答案作成中",
    draft: {
      body: "このたびは「知事への手紙」にご意見をお寄せいただき、ありがとうございます。\n子育て支援センターの土日開放を求めるご意見として拝見いたしました。\n\n県では、子育て世帯を支える環境づくりを重点施策として位置づけ、市町と連携した支援制度の拡充を進めているところです。子育て支援センターの開館日・開館時間は運営主体である市町において決定されておりますが、共働き世帯の利用機会の確保は県全体の課題と認識しており、いただいたご意見は市町との連絡会議の場で共有し、休日開放の先行事例の横展開を検討してまいります。\n\n今後とも、県民の皆さまの声を大切にした県政運営に努めてまいりますので、引き続きお気づきの点がございましたらお聞かせください。\n\n（所管：子ども若者部）",
      generatedAt: "2026-07-10 11:08",
      generator: "AI",
      edited: false,
    },
    log: [
      {
        at: "2026-07-10 11:05",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-10 11:08",
        action: "AIが回答案を生成",
        by: "システム",
      },
    ],
  },
  {
    id: "LTR-2026-0331",
    receivedAt: "2026-07-09 08:50",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "50代",
    senderArea: "高島市",
    body: "自宅近くの山際で今年に入ってから3回クマの目撃情報がありました。通学路にも近く、子どもたちが心配です。目撃情報の共有をもっと早くしてほしいのと、捕獲や追い払いの体制を強化してください。",
    aiSummary: "クマ出没多発地域における目撃情報の迅速な共有と捕獲・追い払い体制強化の要望",
    aiPoints: [
      "今年3回の目撃情報、通学路に近接し児童への危険を懸念",
      "情報共有の迅速化と対応体制の強化を要望",
      "獣害関連の意見は今月14件と急増中",
    ],
    sentiment: "要望",
    aiConfidence: 92,
    category: "防災・安全",
    department: "防災危機管理局",
    priority: "高",
    aiPriorityReason:
      "人身被害につながる恐れがあり、通学路への近接など緊急性が高いため",
    replyRequired: true,
    status: "決裁待ち",
    draft: {
      body: "このたびは「知事への手紙」にご意見をお寄せいただき、ありがとうございます。\nクマの目撃情報の迅速な共有と、捕獲・追い払い体制の強化を求めるご意見として拝見いたしました。\n\n県民の皆さまの安全・安心の確保は県政の基本であり、クマをはじめとする野生獣の出没に対しては、市町・警察・猟友会と連携した対応体制を整えているところです。目撃情報につきましては、防災アプリおよびLINE公式アカウントでの即時配信を今年度中に開始する準備を進めております。また、出没が続く地域では、市町と連携した追い払い・捕獲体制の強化と、通学路周辺の緩衝帯整備を進めてまいります。\n\n今後とも、県民の皆さまの声を大切にした県政運営に努めてまいりますので、引き続きお気づきの点がございましたらお聞かせください。\n\n（所管：防災危機管理局）",
      generatedAt: "2026-07-09 09:02",
      generator: "AI",
      edited: true,
      approvalRequestedAt: "2026-07-11 13:30",
    },
    log: [
      {
        at: "2026-07-09 08:50",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-09 09:02",
        action: "AIが回答案を生成",
        by: "システム",
      },
      {
        at: "2026-07-11 13:28",
        action: "回答案を編集（情報配信の開始時期を追記）",
        by: "広報課 県民の声担当",
      },
      {
        at: "2026-07-11 13:30",
        action: "決裁を依頼（広報課長）",
        by: "広報課 県民の声担当",
      },
    ],
  },
  {
    id: "LTR-2026-0330",
    receivedAt: "2026-07-08 15:12",
    channel: "郵送",
    senderName: "西村 幸一",
    senderAgeGroup: "60代",
    senderArea: "近江八幡市",
    body: "観光シーズンになると自宅周辺の道路が観光客の車で渋滞し、生活に支障が出ています。臨時駐車場の案内やパークアンドライドなど、地元住民の生活と観光の両立を考えた対策をお願いします。",
    aiSummary: "観光地周辺の渋滞対策（臨時駐車場案内・パークアンドライド等）の要望",
    aiPoints: [
      "観光シーズンの渋滞による生活影響",
      "パークアンドライド等の具体策を提案",
    ],
    sentiment: "要望",
    aiConfidence: 88,
    category: "産業・観光",
    department: "商工観光労働部",
    priority: "中",
    aiPriorityReason:
      "生活への影響はあるが季節性の課題であり、計画的な対策が可能なため",
    replyRequired: true,
    status: "回答済",
    draft: {
      body: "このたびは「知事への手紙」にご意見をお寄せいただき、ありがとうございます。\n観光地周辺の渋滞対策を求めるご意見として拝見いたしました。\n\n県では、地域経済の活性化と持続可能な観光地域づくりに取り組んでおり、観光客の集中による生活環境への影響は重要な課題と認識しております。ご提案いただいたパークアンドライドにつきましては、今年度、近江八幡市および交通事業者と連携した実証実験を秋の観光シーズンに実施する方向で調整を進めております。あわせて、リアルタイムの駐車場満空情報の発信強化にも取り組んでまいります。\n\n今後とも、県民の皆さまの声を大切にした県政運営に努めてまいりますので、引き続きお気づきの点がございましたらお聞かせください。\n\n（所管：商工観光労働部）",
      generatedAt: "2026-07-08 16:20",
      generator: "AI",
      edited: true,
      approvalRequestedAt: "2026-07-09 10:15",
      sentAt: "2026-07-10 14:00",
    },
    log: [
      {
        at: "2026-07-08 15:12",
        action: "郵送で受領、職員がスキャン登録後にAIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-08 16:20",
        action: "AIが回答案を生成",
        by: "システム",
      },
      {
        at: "2026-07-09 10:15",
        action: "決裁を依頼（広報課長）",
        by: "広報課 県民の声担当",
      },
      {
        at: "2026-07-10 14:00",
        action: "決裁完了、回答を送付",
        by: "広報課長",
      },
    ],
  },
  {
    id: "LTR-2026-0329",
    receivedAt: "2026-07-08 10:44",
    channel: "Webフォーム",
    senderName: "佐々木 隼人",
    senderAgeGroup: "20代",
    senderArea: "東近江市",
    body: "県外から移住を検討しています。移住支援金の対象要件がWebサイトを見てもわかりにくく、自分が対象になるのか判断できませんでした。チェックリストやチャットで確認できる仕組みがあると助かります。",
    aiSummary: "移住支援金の対象要件のわかりにくさ改善（チェックリスト・チャット確認）の提案",
    aiPoints: [
      "Webサイトの要件説明がわかりにくく対象判定ができない",
      "セルフチェックの仕組みを具体的に提案",
    ],
    sentiment: "提案",
    aiConfidence: 85,
    category: "県政運営・手続",
    department: "総合企画部",
    priority: "低",
    aiPriorityReason:
      "案内改善の提案であり、緊急性・影響範囲ともに限定的なため",
    replyRequired: true,
    status: "回答済",
    draft: {
      body: "このたびは「知事への手紙」にご意見をお寄せいただき、ありがとうございます。\n移住支援金の対象要件のわかりやすい案内を求めるご意見として拝見いたしました。\n\n県政の運営や手続きに関する貴重なご意見をいただき、ありがとうございます。ご指摘を踏まえ、移住支援金のWebページに対象要件を順に確認できるセルフチェック形式の案内を追加する改修を行うことといたしました（今年8月公開予定）。また、移住相談窓口ではオンライン相談も受け付けておりますので、個別のご事情についてはぜひご利用ください。\n\n今後とも、県民の皆さまの声を大切にした県政運営に努めてまいりますので、引き続きお気づきの点がございましたらお聞かせください。\n\n（所管：総合企画部）",
      generatedAt: "2026-07-08 11:00",
      generator: "AI",
      edited: true,
      approvalRequestedAt: "2026-07-08 15:40",
      sentAt: "2026-07-09 09:30",
    },
    log: [
      {
        at: "2026-07-08 10:44",
        action: "Webフォーム経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-08 11:00",
        action: "AIが回答案を生成",
        by: "システム",
      },
      {
        at: "2026-07-08 15:40",
        action: "決裁を依頼（広報課長）",
        by: "広報課 県民の声担当",
      },
      {
        at: "2026-07-09 09:30",
        action: "決裁完了、回答を送付",
        by: "広報課長",
      },
    ],
  },
  {
    id: "LTR-2026-0328",
    receivedAt: "2026-07-07 17:26",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "10代",
    senderArea: "米原市",
    body: "学校の校外学習で琵琶湖博物館に行きました。展示がとても面白くて、特に淡水魚の水槽が良かったです。案内してくれたスタッフの方も優しかったです。ありがとうございました。",
    aiSummary: "琵琶湖博物館の展示・スタッフ対応への感謝の声",
    aiPoints: [
      "校外学習での来館体験に対する好意的な感想",
      "回答不要と判定（感謝の声として記録・共有）",
    ],
    sentiment: "感謝",
    aiConfidence: 97,
    category: "環境・琵琶湖",
    department: "琵琶湖環境部",
    priority: "低",
    aiPriorityReason:
      "感謝の声であり、対応の緊急性はないため",
    replyRequired: false,
    status: "回答不要",
    log: [
      {
        at: "2026-07-07 17:26",
        action: "LINE経由で受信、AIが要約・振り分けを実行",
        by: "システム",
      },
      {
        at: "2026-07-07 17:50",
        action: "感謝の声として記録し、琵琶湖博物館に共有（回答不要）",
        by: "広報課 県民の声担当",
      },
    ],
  },
];

/** 「LINE受信をシミュレート」で順に届くデモ用の手紙 */
export const incomingPool: Omit<Letter, "receivedAt" | "log" | "isFresh">[] = [
  {
    id: "LTR-2026-0342",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "30代",
    senderArea: "栗東市",
    body: "学童保育の待機児童が増えていると聞きます。うちも来年から小学生ですが入れるか不安です。指導員の確保への支援など、県としてできることを進めてほしいです。",
    aiSummary: "学童保育の待機児童解消に向けた指導員確保支援の要望",
    aiPoints: [
      "来年度の入所可否への不安が動機",
      "指導員確保への県支援を要望",
    ],
    sentiment: "要望",
    aiConfidence: 90,
    category: "子育て・教育",
    department: "子ども若者部",
    priority: "中",
    aiPriorityReason:
      "来年度に向けた制度要望で、対応を検討する時間的余裕があるため",
    replyRequired: true,
    status: "新着",
  },
  {
    id: "LTR-2026-0343",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "40代",
    senderArea: "日野町",
    body: "県道沿いの街灯が少なく、夜間に歩くのが怖いという声が地域で出ています。部活帰りの中高生も通る道です。街灯の増設を検討してもらえないでしょうか。",
    aiSummary: "県道沿いの街灯増設の要望（夜間の通学・歩行の安全確保）",
    aiPoints: [
      "夜間の歩行に不安を感じる地域の声",
      "中高生の帰宅路であることを指摘",
    ],
    sentiment: "要望",
    aiConfidence: 89,
    category: "道路・交通",
    department: "土木交通部",
    priority: "中",
    aiPriorityReason:
      "夜間の安全に関わるが事故報告はなく、計画的な対応が可能なため",
    replyRequired: true,
    status: "新着",
  },
  {
    id: "LTR-2026-0344",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "50代",
    senderArea: "彦根市",
    body: "介護施設で働いていますが、人手不足が深刻で、このままでは利用者の受け入れを減らさざるを得ません。処遇改善や外国人材の受け入れ支援など、県の対策を強化してください。",
    aiSummary: "介護人材不足への対策強化（処遇改善・外国人材受入支援）の要望",
    aiPoints: [
      "現場職員からの人手不足の切実な訴え",
      "受け入れ縮小の可能性に言及、緊急性が高い",
    ],
    sentiment: "要望",
    aiConfidence: 92,
    category: "医療・福祉",
    department: "健康医療福祉部",
    priority: "高",
    aiPriorityReason:
      "サービス縮小の可能性への言及があり、現場からの緊急性の高い訴えのため",
    replyRequired: true,
    status: "新着",
  },
  {
    id: "LTR-2026-0345",
    channel: "LINE",
    senderName: "匿名",
    senderAgeGroup: "20代",
    senderArea: "大津市",
    body: "外国人の友人と観光地を回りましたが、案内表示の英語が少なく、バスの乗り方も分かりにくいと言われました。多言語の案内表示やデジタルマップの整備を進めてほしいです。",
    aiSummary: "観光地の多言語案内表示・デジタルマップ整備の要望",
    aiPoints: [
      "外国人観光客目線での案内不足の指摘",
      "多言語表示とデジタルマップの2つの改善案",
    ],
    sentiment: "提案",
    aiConfidence: 87,
    category: "産業・観光",
    department: "商工観光労働部",
    priority: "低",
    aiPriorityReason:
      "中長期的な環境整備の提案であり、緊急性は低いため",
    replyRequired: true,
    status: "新着",
  },
];

/** 頻出テーマ（直近30日・AIクラスタリング結果のデモ表示用） */
export const seedThemes: Theme[] = [
  {
    id: "THM-01",
    title: "子ども医療費助成の対象拡大",
    category: "子育て・教育",
    count: 32,
    trend: "急増",
    weeklySeries: [2, 3, 3, 4, 5, 7, 8, 9, 11, 14, 18, 32],
    sample: "隣県並みに高校卒業まで無料にしてほしい",
  },
  {
    id: "THM-02",
    title: "路線バス減便・地域交通の確保",
    category: "道路・交通",
    count: 27,
    trend: "増加",
    weeklySeries: [8, 9, 9, 10, 12, 13, 15, 16, 18, 21, 24, 27],
    sample: "高齢の親が通院できなくなりつつある",
  },
  {
    id: "THM-03",
    title: "琵琶湖岸の水草・悪臭対策",
    category: "環境・琵琶湖",
    count: 21,
    trend: "増加",
    weeklySeries: [3, 3, 4, 5, 6, 8, 10, 12, 14, 17, 19, 21],
    sample: "岸に打ち上がった水草の腐敗臭がひどい",
  },
  {
    id: "THM-04",
    title: "通学路・県道の歩道整備",
    category: "道路・交通",
    count: 18,
    trend: "横ばい",
    weeklySeries: [12, 13, 14, 13, 14, 15, 15, 16, 16, 17, 17, 18],
    sample: "歩道が狭くガードレールのない区間が危険",
  },
  {
    id: "THM-05",
    title: "クマ・獣害対策",
    category: "防災・安全",
    count: 14,
    trend: "急増",
    weeklySeries: [1, 1, 2, 2, 3, 3, 4, 6, 8, 10, 12, 14],
    sample: "目撃情報の共有をもっと早くしてほしい",
  },
  {
    id: "THM-06",
    title: "県立高校の再編・魅力化",
    category: "子育て・教育",
    count: 12,
    trend: "横ばい",
    weeklySeries: [9, 9, 10, 10, 11, 10, 11, 11, 12, 12, 11, 12],
    sample: "保護者への説明の機会を増やしてほしい",
  },
  {
    id: "THM-07",
    title: "介護・医療人材の確保",
    category: "医療・福祉",
    count: 11,
    trend: "増加",
    weeklySeries: [4, 4, 5, 5, 6, 6, 7, 8, 9, 10, 10, 11],
    sample: "人手不足で利用者の受け入れを減らさざるを得ない",
  },
  {
    id: "THM-08",
    title: "観光地の渋滞・オーバーツーリズム",
    category: "産業・観光",
    count: 9,
    trend: "横ばい",
    weeklySeries: [6, 6, 7, 7, 8, 7, 8, 8, 9, 8, 9, 9],
    sample: "観光シーズンの渋滞で生活に支障が出ている",
  },
];

/** 月別受付件数（直近12ヶ月・デモ用） */
export const monthlySeries = {
  labels: [
    "8月",
    "9月",
    "10月",
    "11月",
    "12月",
    "1月",
    "2月",
    "3月",
    "4月",
    "5月",
    "6月",
    "7月",
  ],
  values: [58, 62, 55, 60, 71, 66, 74, 82, 88, 95, 103, 118],
};

/** チャネル別内訳（今月・デモ用） */
export const channelBreakdown = [
  { label: "LINE", value: 74, color: "#0f172a" },
  { label: "Webフォーム", value: 21, color: "#475569" },
  { label: "メール", value: 14, color: "#94a3b8" },
  { label: "郵送", value: 9, color: "#cbd5e1" },
];

/** 部局別の対応状況（今月・デモ用） */
export const departmentStats: {
  department: Department;
  received: number;
  unanswered: number;
  avgDays: number;
}[] = [
  { department: "子ども若者部", received: 26, unanswered: 6, avgDays: 3.8 },
  { department: "土木交通部", received: 24, unanswered: 7, avgDays: 5.1 },
  { department: "琵琶湖環境部", received: 17, unanswered: 3, avgDays: 3.4 },
  { department: "健康医療福祉部", received: 15, unanswered: 4, avgDays: 4.6 },
  { department: "商工観光労働部", received: 12, unanswered: 2, avgDays: 3.9 },
  { department: "防災危機管理局", received: 10, unanswered: 3, avgDays: 2.8 },
  { department: "教育委員会", received: 8, unanswered: 2, avgDays: 5.4 },
  { department: "総合企画部", received: 6, unanswered: 1, avgDays: 3.1 },
];

export const weeklySeriesLabels = [
  "4/20週",
  "4/27週",
  "5/4週",
  "5/11週",
  "5/18週",
  "5/25週",
  "6/1週",
  "6/8週",
  "6/15週",
  "6/22週",
  "6/29週",
  "7/6週",
];
